---
title: "Project"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
     collapsed: false
     smooth_scroll: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br><br><br>

## 2019

#### **[In porgress]** Bayesian model averaging approach for RNA-seq counts data (BMA-seq) and its application

+ Assist the advisor with developing a new statistical method using Bayesian model averaging to identify differentially expressed genes associated with one or more phenotypes, as well as their interactions.
+ Develop R package `BMAseq` using Bayesian model averaging to analyze observational gene-expression data
+ Apply the Bayesian model averaging method to large scale public RNA-seq gene expression data
+ Apply the Bayesian model averaging method (`BMA-seq`) to observational metabolomics data to improve differentially expressed (DE) metabolites identification in high dimensional setting

<br>

#### **[In progress]** Liver transcriptome map of air pollution $PM_{2.5}$

+ Main interests: Gender and aging effect
+ Time point: Wk05 and Wk17
+ Gender: Male and Female
+ Groups: Chow FA, Chow PM, High fat diet FA, and High fat diet PM

<br>

#### **[In progress]** Brain transcriptome map of air pollution $PM_{2.5}$

+ Construct data pipeline of both EdgeR and DESeq2 to identify differentially expressed genes associated with the exposure to ultra-fine dust, PM2.5
+ Check the distribution by Relative Log Expression (RLE) and Principal Component Analysis (PCA) plots
+ Normalize each sample and removed unwanted variances and filtered top 5,000 genes by p-values from EdgeR and DESeq2
+ Perform DE (Differential Expression) analysis using EdgeR and Gene Ontology (GO) Term analysis on six different brain sub-areas and liver cells.
+ Conduct pathway analysis using Ingenuity Pathway Analysis (IPA) software

<br>

#### The Effect of Right Heart Catheterization (RHC) During the First 24 Hours on 30-day Mortality of Critically Ill Patients in Intensive Care Units

+ [Paper](/content/project/RHC_paper.pdf)

<br>

#### Reproduction of SDY210 clinical trial

**Adding Exhaled Nitric Oxide to Guideline-based Asthma Treatment in Inner-City Adolescents and Young Adults: a Randomized Controlled Trial**

+ Original study: [SDY210](https://www.immport.org/shared/study/SDY210)
+ [Paper](/content/project/SDY210_paper.pdf)
+ [Slide](/content/project/SDY210_slide.pdf)

<br>

#### Rate Of General Anesthesia Use For Cesarean Delivery Among Anesthesiologists With And Without Fellowship Training in Obstetric Anesthesia

This report presents a retrospective statistical analysis of cesarean delivery among attending anesthesiologists with and without fellowship training in obstetric anesthesia who were seen at the NYP between 2009 and 2014 and had their rate of general anesthesia use assessed. Demographic, training / service experience, and outcomes of anesthesia were summarized. Logistic regression model was used to identify whether the fellowship-trained anesthesiologists are more or less likely to provide general anesthesia for non-routine c-section as compared to non-fellowship trained anesthesiologists.

+ [Report](/content/project/anesthesia_paper.pdf)
+ [Slide](/content/project/anesthesia_slide.pdf)

<br>

#### Cost-Effective Optimization of Model-Based Prediction of Cardiovascular Disease (CVD)

Determine the demographics and medical tests that help predict the likelihood and optimize in a cost-effective manner.

+ [Poster](/content/project/CVD_poster.pdf)

<br><br>

***

## 2018

<br>

#### Neuroendrocine prostate cancer (NEPC)

Identify the clinical characteristics and molecular profiles of responding patients to define distinct cohorts most likely to benefit.

+ [Paper](/content/project/NEPC_paper.pdf)
+ [Slide](/content/project/NEPC_slide.pdf)

<br>

#### Major Risk Factors of Low Birth Weight Babies

+ [Paper](/content/project/lowbirthweight.pdf)

<br>

#### Study design of Tommy John Surgery for MLB Pitchers by *Statcast* Measurements

**Primary Injury Factors of Ulnar Collateral Ligament Reconstruction for Major League Baseball Pitchers by Statcast Measures**

Design a study to identify major factors of Ulnar Collateral Ligament Reconstruction (a.k.a. Tommy John Surgery) for Major League Baseball Pitchers by Statcast Measures

+ [Paper](/content/project/TJS_paper.pdf)
+ [Slide](/content/project/TJS_slide.pdf)

