---
pagetitle: "[Research]"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
     collapsed: false
     smooth_scroll: false
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="site_libs/academicons-1.9.1/css/academicons.min.css"/>

<br><br><br>

For the most up to date list of publications, check out my [Google Scholar](https://scholar.google.com/citations?user=BM4yFdAAAAAJ&hl=en) or [Researchgate](https://www.researchgate.net/profile/Taehoon-Ha-3) page.

<br>

### Published

+ Ann-Margaret Navarra, **Taehoon Ha**, Eva Liang, Maurade Gormley, David R. Garcia, Jason Fletcher, Lloyd A. Goldsamt, Michael G. Rosenberg, Karin Hasegawa, and Jie Yang (2025). [*Characterization of Antiretroviral Therapy (ART) Adherence Phenotypes and Psychosocial Symptom Clusters Among Black/African American (AA) and Hispanic/Latine Adolescents and Young Adults (AYAs) with HIV in the Adherence Connection for Counseling, Education, and Support (ACCESS-II) Trial*](https://doi.org/10.3390/tropicalmed10120332). Trop. Med. Infect. Dis.

+ Olaf Klingbeil, Damianos Skopelitis, Claudia Tonelli, Toyoki Yoshimoto, Aktan Alpsoy, Maria Panepinto, Francesca Minicozzi, Joseph Merrill, Amanda Cafiero, Disha Aggarwal, Suzanne Russo, **Taehoon Ha**, Osama Demerdash, David Spector, Scott Lyons, David Tuveson, Paolo Cifani, and Christopher Vakoc (2024). [*MARK2/MARK3 kinases are catalytic co-dependencies of YAP/TAZ in human cancer*](https://doi.org/10.1158/2159-8290.CD-23-1529). Cancer Discovery.

+ Edward Zhou, Jung-In Yang, Amber Habowski, Astrid Deschênes, Pascal Belleau, **Taehoon Ha**, Chris Tzanavaris, Jeff Boyd, Christopher Hollweg, Xinhua Zhu, David Tuveson, and Daniel A. King (2024). [*GATA6 Amplification is Associated with Improved Survival of TP53-Mutated Pancreatic Cancer*](https://doi.org/10.1097/MPA.0000000000002431). Pancreas.

+ Samantha Henry, Steven M. Lewis, Samantha L. Cyrill, Mackenzie K. Callaway, Deeptiman Chatterjee, Amritha V. H. Somasundara, Gina Jones, Xue-Yan He, Giuseppina Caligiuri, Michael F. Ciccone, Isabella A. Diaz, Amelia Biswas, Evelyn Hernandez, **Taehoon Ha**, John E. Wilkinson, Mikala E. Egeblad, David A. Tuveson, Camila O. dos Santos (2024). [*Host response during unresolved urinary tract infection alters mammary tissue homeostasis through collagen deposition and TIMP1*](https://doi.org/10.1038/s41467-024-47462-7). Nature Communications.

+ Yuan Gao, Xue-Yan He, Xiaoli S. Wu, Yu-Han Huang, Shushan Toneyan, Jonathan J. Ipsaro, **Taehoon Ha**, Peter K. Koo, Mikala Egeblad, Leemor Joshua-Tor, and Christopher R. Vakoc (2023). [*ETV6 dependency in Ewing sarcoma through antagonism of EWS-FLI1- mediated enhancer activation*](https://doi.org/10.1038/s41556-022-01060-1). Nature Cell Biology.

+ Sonam Bhatia, Melissa Kramer, Suzanne Russo, Payal Naik, Gayatri Arun, Kyle Brophy, Peter Andrews, Cheng Fan, Charles Perou, Jonathan Preall, **Taehoon Ha**, Dennis Plenker, David Tuveson, Arvind Rishi, John Wilkinson, W. Richard McCombie, Karen Kostroff, and David Spector (2022). [*Patient-derived triple negative breast cancer organoids provide robust model systems that recapitulate tumor intrinsic characteristics*](https://doi.org/10.1158/0008-5472.CAN-21-2807). Cancer Research.

+ Christina M Brennan, Sandeep Nadella, Xiang Zhao, Richard J Dima, Nicole Jordan-Martin, Breanna R Demestichas, Sam O Kleeman, Miriam Ferrer, Eva Carlotta von Gablenz, Nicholas Mourikis, Michael E Rubin, Harsha Adnani, Hassal Lee, **Taehoon Ha**, Soma Prum, Cheryl B Schleicher, Sharon S Fox, Michael G Ryan, Christina Pili, Gary Goldberg, James M Crawford, Sara Goodwin, Xiaoyue Zhang, Jonathan B Preall, Ana S H Costa, Joseph Conigliaro, Joseph R Masci, Jie Yang, David A Tuveson, Kevin J Tracey, and Tobias Janowitz (2022). [*Oral famotidine versus placebo in non-hospitalised patients with COVID-19: a randomised, double-blind, data-intense, phase 2 clinical trial*](http://dx.doi.org/10.1136/gutjnl-2022-326952). Gut.

+ Srijani Basu, Catherine Liu, Xi Kathy Zhou, Nishiguchi Ryohei, **Taehoon Ha**, Justin Chen, Melanie Johncilla, Rhonda K. Yantiss, David C. Montrose and Andrew J. Dannenberg (2021). [*GLUT5 is a Determinant of Dietary Fructose-mediated Exacerbation of Experimental Colitis*](https://doi.org/10.1152/ajpgi.00059.2021). AJP Gastrointestinal and Liver Physiology.

+ Jung-In Yang, **Taehoon Ha**, Edward Zhou, Chris Tzanavaris, Craig E. Devoe, Xinhua Zhu, and Jeff Boyd (2021). [*Association of TP53 mutation status and GATA6 amplification with clinical outcome of pancreatic cancer*](http://doi.org/10.1200/JCO.2021.39.15_suppl.e16224). Journal of Clinical Oncology [2021 ASCO Annual Meeting].

+ David C. Montrose, Suchandrima Saha, Miguel Foronda, Erin M. McNally, Justin Chen, Xi Kathy Zhou, **Taehoon Ha**, Jan Krumsiek, Mustafa Buyukozkan, Akanksha Verma, Olivier Elemento, Rhonda K. Yantiss, Qiuying Chen, Steven S. Gross, Lorenzo Galluzzi, Lukas E. Dow and Andrew J. Dannenberg (2021). [*Exogenous and Endogenous Sources of Serine Contribute to Colon Cancer Metabolism, Growth and Resistance to 5-Fluorouracil*](https://doi.org/10.1158/0008-5472.CAN-20-1541). Cancer Research.

+ Neil M. Iyengar, Xi Kathy Zhou, Hillary Mendieta, Omar El-Hely, Dilip D. Giri, Lisle A. Winston, Domenick J. Falcone, Hanhan Wang, Lingsong Meng, **Taehoon Ha**, Michael Pollak, Clifford A. Hudis, Monica Morrow, and Andrew J. Dannenberg (2021). [*Effects of Obesity on Breast Aromatase Expression and Systemic Metabo-Inflammation in Women with BRCA1 or BRCA2 Mutations*](https://doi.org/10.1038/s41523-021-00226-8). npj Breast Cancer.

+ Ryohei Nishiguchi, Srijani Basu, Hannah A. Staab, Naotake Ito, Xi Kathy Zhou, Hanhan Wang, **Taehoon Ha**, Melanie Johncilla, Rhonda K. Yantiss, David C. Montrose and Andrew J. Dannenberg (2021). [*Dietary Interventions to Prevent High Fructose Diet-associated Worsening of Colitis and Colitis-associated Tumorigenesis in Mice*](https://doi.org/10.1093/carcin/bgab007). Carcinogenesis.

+ Edward H. Williams, Thomas R. Flint, Claire M. Connell, Daniel Giglio, Hassal Lee, **Taehoon Ha**, Eva Gablenz,  Nicholas Bird, James M. J. Weaver, Harry Potts, Cameron T. Whitley, Michael A. Bookman, Andy G. Lynch, Hannah V. Meyer, Simon Tavaré, and Tobias Janowitz (2020). [*CamGFR v2: A New Model for Estimating the Glomerular Filtration Rate from Standardized or Non-Standardized Creatinine in Patients with Cancer*](https://doi.org/10.1158/1078-0432.CCR-20-3201). Clinical Cancer Research.

<style>
div.box { background-color:#F6F6F6; border-radius: 5px; padding: 20px;}
</style>
<div class = "box">
<strong>Shiny App</strong> <br>

The glomerular filteration rate (GFR) estimate model is available as an online tool [HERE](https://sites.google.com/site/janowitzwilliamsgfr/). The default setting assumes that creatinine has been determined using an isotope dilution mass spectrometry (IDMS) calibrated method.
</div>

<br><br>

### Accepted

<br><br>

### Submitted
+ Oliver J. Standring, Julien T. Hohenleitner, Lyudmyla Demyan, Shruti Koti, Nandan Vithlani, Taemoon Chung, Amber N. Habowski, **Taehoon Ha**, Sepideh Gholami, James M. Crawford, Youngkyu Park, Oliver Jonas, Zhen Zhao, Scott Lyons, Daniel A. King, David A. Tuveson, and Matthew J. Weiss (2026). [*Implantable Microdevices for In Vivo Assessment of Chemotherapy Response in Patient Derived Organoid Orthotopic Pancreatic Cancer Models*](https://journals.lww.com/annalsofsurgery/pages/default.aspx). Annals of Surgery.

+ Noah J. Lubin, Alfonse Mazzarella, Matthew Chan, Daniella Lorman, Seyed Morsal Mosallami Aghili, **Taehoon Ha**, Charles Mikell, and Sima Mofakham (2026). [*Residence-Based Geospatial Analysis of Severe Traumatic Brain Injury in a Regional Neurotrauma System*](https://www.sciencedirect.com/journal/world-neurosurgery). World Neurosurgery.

+ John Servider, Noah Lubin, Justin Passman, Claire Kim, Peter Gerace, Richard Rosin, Gregory Sacks, Vaidehi Patel, **Taehoon Ha**, Susan Fiore, Raphael Davis, and Harry Mushlin (2026). [*Incidence and Risk Factors for Venous Thromboembolism in Elective Lumbar Spine Patients with Standardized Post-Operative Dopplers: A Single-Center Review*](https://journals.sagepub.com/home/GSJ). Global Spine Journal.

+ John Servider, Noah Lubin, Justin Passman, Richard Rosin, Ryan Lebens, Claire Parker, Gregory Sacks, **Taehoon Ha**, Susan Fiore, and Harry Mushlin (2026). [*Abdominal Aortic Atherosclerosis and Lumbar Bone Density: A Quantitative Analysis*](https://journals.sagepub.com/home/GSJ). Global Spine Journal.

+ Andrea Allmer Kabacinski, Amanda Groveman, Natalie Rivas, Julie Luengas, **Taehoon Ha**, Jie Yang, and Meghan Doelger (2026). [*Reproducibility in Practice: Validation of a Predictive Fall Risk Model in a New Electronic Health Record Environment*](https://www.jointcommissionjournal.com/). The Joint Commission Journal on Quality and Patient Safety.

+ Bayan Razzaq, Robert Kleyner, **Taehoon Ha**, Justin Passman, Kevin Gilotra, John Servider, Jermaine Roberston, Sujith Swarna, Sima Mofakham, Charles Mikell III, and Harry Mushlin (2026). [*CT Marshall Score as a Potential Clinical Decision Tool for Invasive Intracranial Monitoring in Severe Traumatic Brain Injury*](https://thejns.org/). Journal of Neurosurgery.

<br><br>
