---
pagetitle: "Speaking"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
     collapsed: false
     smooth_scroll: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br><br>

### Interview

+ Analysis of 3,600 COVID-19 sequences on Nextstrain (April 28th, 2020), Donga Science [[Link](https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=103&oid=584&aid=0000008582)]


<br><br>

### Presentation
+ Virtual Core Knowledge: Biostatistics Workshop 01/21/2021, Cold Spring Harbor Laboratory [[Slide](/content/post/VirtualCoreKnowledgeWorkshop_Biostatistics_01212021.pdf)]

+ Journal Club 03/02/2020, Weill Cornell Medicine: The Single-cell Pathology Landscape of Breast Cancer [[Slide](/content/post/Journal Club 03_02 Presentation Slide.pdf)]

+ Journal Club 12/02/2019, Weill Cornell Medicine: Genomic Signatures Predict the Immunogenicity of BRCA-Deficient Breast Cancer [[Slide](/content/post/Journal Club 12_02 Presentation Slide.pdf)]

+ Journal Club 08/26/2019, Weill Cornell Medicine: Profound Perturbation of the Metabolome in Obesity Is Associated with Health Risk [[Slide](/content/post/Journal Club 08_26 Presentation Slide.pdf)]