---
pagetitle: "Writing"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
     collapsed: false
     smooth_scroll: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br><br><br>

### Technical translation

+ Genomic analysis of COVID-19 spread. Situation report 2020-05-08 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-05-08)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/en/2020-05-08)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-05-01 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-05-01)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/en/2020-05-01)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-04-24 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-24)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/en/2020-04-24)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-04-17 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-17)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/en/2020-04-17)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-04-10 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-10)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/en/2020-04-10)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-04-03 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Apr. 2020)      
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-03)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/2020-04-03)]

+ Genomic analysis of COVID-19 spread. Situation report 2020-03-27 (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Mar. 2020)   
[[Korean](https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-03-27)] [[English](https://nextstrain.org/narratives/ncov/sit-rep/2020-03-27)]

+ How to interpret phylogenetic trees (Korean ver.), [*Nextstrain*](https://nextstrain.org/) (Mar. 2020) [[Korean](https://nextstrain.org/narratives/trees-background/ko)] [[English](https://nextstrain.org/narratives/trees-background/)]

<br><br>


### Miscellaneous
+ [Alternative to kable function when knitting to MS word](/content/post/alternative-to-kable-function-when-knitting-to-ms-word.html)

+ [Monte Carlo simulation for causal inference( G-computation formula)](/content/post/Monte-Carlo-simulation-for-causal-inference.html)

+ [Summary of `data.table`](/content/post/data.table.html)